// <auto-generated />
namespace RestaurantSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dayaccountings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dayaccountings));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141851028_dayaccountings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
